sonar.projectKey=magiceagle7707-oss_ai-interview-platform
sonar.organization=magiceagle7707-oss

sonar.sources=src
sonar.tests=src/test
sonar.exclusions=src/test/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
